import Head from 'next/head'
import { Inter } from '@next/font/google'
import Link from 'next/link'
import { Checkbox } from 'antd';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        This page hasn't layoyt
        <div>
          <Link href="/owner">owner</Link>
        </div>
        <div>
          <Link href="/admin">admin</Link>
        </div>
        <Link href="/candidate">candidate</Link>
        <Checkbox>Checkbox</Checkbox>;
      </main>
    </>
  )
}
